import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Success!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>

       <h1>Congratulation! You are on my little App! Listen to my contact below.</h1>
      <div style="left:0;width:100%;height:0;position:relative;padding-bottom:100%">
          <iframe src="https://mote.com/m/sf448wn?embed=true" style="top:0;left:0;width:100%;height:100%;position:absolute;border:0" title="Mote" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"></iframe>
      </div>
  <p>You've completed the essentials of automated application deployment with GitHub Actions! 🥳</p>

      </main>
    </>
  )
}
